name: Pull Requests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main

jobs:
  detect-changes:
    name: Determine modified rocks
    runs-on: ubuntu-24.04
    outputs:
      versions: ${{ steps.changed-versions.outputs.versions }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find changed files in version directories
        id: changed-files
        uses: tj-actions/changed-files@2f7c5bfce28377bc069a65ba478de0a74aa0ca32 # v46.0.1
        with:
          files: |
            **/rockcraft.yaml
            **/files/**

      - name: Extract the versions
        id: changed-versions
        run: ./scripts/extract-versions.sh ${{ steps.changed-files.outputs.all_changed_files }}

  build-and-test:
    name: Pack and test rocks on ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.runner-labels }}
    needs: [detect-changes]
    if: needs.detect-changes.outputs.versions != ''
    strategy:
      fail-fast: true
      matrix:
        # Define 'platform' as an object containing both metadata and labels
        platform:
          - name: Ubuntu amd64 24.04
            runner-labels: [ubuntu-24.04]
          - name: Ubuntu arm64 24.04
            runner-labels: [ubuntu-24.04-arm]
          - name: Ubuntu s390x 24.04
            runner-labels: [self-hosted-linux-s390x-noble-medium]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup LXD
        uses: canonical/setup-lxd@main

      - name: Install rockcraft
        run: sudo snap install rockcraft --classic --channel=latest/candidate

      - name: Install goss
        run: curl -fsSL https://goss.rocks/install | sh

      - name: Pack and test rocks
        run: |
          GOSS_FILES_PATH="$GITHUB_WORKSPACE" \
            ./scripts/pack-and-test.sh ${{ needs.detect-changes.outputs.versions }}
