name: Pull Requests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main

jobs:
  detect-changes:
    name: Determine modified rocks
    runs-on: ubuntu-24.04
    outputs:
      versions: ${{ steps.changed-versions.outputs.versions }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find changed files in version directories
        id: changed-files
        uses: tj-actions/changed-files@2f7c5bfce28377bc069a65ba478de0a74aa0ca32 # v46.0.1
        with:
          files: |
            **/rockcraft.yaml
            **/files/**

      - name: Extract the versions
        id: changed-versions
        run: ./scripts/extract-versions.sh ${{ steps.changed-files.outputs.all_changed_files }}

  build-and-test:
    name: Pack and test rocks on ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.runner-labels }}
    needs: [detect-changes]
    if: needs.detect-changes.outputs.versions != ''
    strategy:
      fail-fast: true
      matrix:
        # Define 'platform' as an object containing both metadata and labels
        platform:
          - name: Ubuntu amd64 24.04
            runner-labels: [ubuntu-24.04]
          - name: Ubuntu arm64 24.04
            runner-labels: [ubuntu-24.04-arm]
          - name: Ubuntu s390x 24.04
            runner-labels: [self-hosted-linux-s390x-noble-medium]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up tmate session
        if: runner.debug == 1
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true
          timeout-minutes: 60

      - name: Setup LXD
        uses: canonical/setup-lxd@main

      - name: Install rockcraft
        run: sudo snap install rockcraft --classic --channel=latest/candidate

      - name: Install goss
      #   run: curl -fsSL https://goss.rocks/install | sh
        run: |
          uname -a
          LATEST_URL="https://github.com/goss-org/goss/releases/latest"
          LATEST_EFFECTIVE=$(curl -s -L -o /dev/null ${LATEST_URL} -w '%{url_effective}')
          LATEST=${LATEST_EFFECTIVE##*/}
          
          DGOSS_VER=$GOSS_VER
          
          if [ -z "$GOSS_VER" ]; then
              GOSS_VER=${GOSS_VER:-$LATEST}
              DGOSS_VER='master'
          fi
          if [ -z "$GOSS_VER" ]; then
              echo "ERROR: Could not automatically detect latest version, set GOSS_VER env var and re-run"
              exit 1
          fi
          GOSS_DST=${GOSS_DST:-/usr/local/bin}
          INSTALL_LOC="${GOSS_DST%/}/goss"
          DGOSS_INSTALL_LOC="${GOSS_DST%/}/dgoss"
          touch "$INSTALL_LOC" || { echo "ERROR: Cannot write to $GOSS_DST set GOSS_DST elsewhere or use sudo"; exit 1; }
          
          arch=""
          if [ "$(uname -m)" = "x86_64" ]; then
              arch="amd64"
          elif [ "$(uname -m)" = "aarch32" ]; then
              arch="arm"
          elif [ "$(uname -m)" = "aarch64" ] || [ "$(uname -m)" = "arm64" ]; then
              arch="arm64"
          else
              arch="$(uname -m)"
          fi
          
          url="https://github.com/goss-org/goss/releases/download/$GOSS_VER/goss-linux-$arch"
          
          echo "Downloading $url"
          curl -L "$url" -o "$INSTALL_LOC"
          chmod +rx "$INSTALL_LOC"
          echo "Goss $GOSS_VER has been installed to $INSTALL_LOC"
          echo "goss --version"
          "$INSTALL_LOC" --version
          
          dgoss_url="https://raw.githubusercontent.com/goss-org/goss/$DGOSS_VER/extras/dgoss/dgoss"
          echo "Downloading $dgoss_url"
          curl -L "$dgoss_url" -o "$DGOSS_INSTALL_LOC"
          chmod +rx "$DGOSS_INSTALL_LOC"
          echo "dgoss $DGOSS_VER has been installed to $DGOSS_INSTALL_LOC"

      - name: Pack and test rocks
        run: |
          GOSS_FILES_PATH="$GITHUB_WORKSPACE" \
            ./scripts/pack-and-test.sh ${{ needs.detect-changes.outputs.versions }}
