name: Open a PR to OCI Factory

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      versions:
        description: "Comma-separated list of version directories (e.g. 2.11.0,2.11.3)"
        required: true
        type: string

jobs:
  build-and-release:
    name: Pack, test and release to OCI Factory
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the rock repository
        uses: actions/checkout@v4
        with:
          path: rock

      - name: Setup LXD
        uses: canonical/setup-lxd@main

      - name: Install dependencies
        run: |
          sudo snap install rockcraft --classic  --channel=latest/candidate
          sudo snap install yq
          ./rock/scripts/install-goss.sh

      - name: Pack and test rocks
        run: |
          cd rock
          versions="${VERSIONS//,/ }"
          GOSS_FILES_PATH="$GITHUB_WORKSPACE/rock" \
            ./scripts/pack-and-test.sh $versions
        env:
          VERSIONS: ${{ inputs.versions }}

      - name: Fork sync and clone OCI Factory
        env:
          GH_TOKEN: ${{ secrets.IS_DEVOPS_BOT_TOKEN }}
        run: |
          gh repo sync --force is-devops-bot/oci-factory || \
            gh repo fork canonical/oci-factory --clone=false
          gh repo sync --force is-devops-bot/oci-factory

      - name: Clone the OCI Factory fork
        uses: actions/checkout@v4
        with:
          path: oci-factory
          repository: is-devops-bot/oci-factory
          token: ${{ secrets.IS_DEVOPS_BOT_TOKEN }}

      - name: Generate image.yaml
        id: generate-manifest
        env:
          MANIFEST_FILE: ${{ github.workspace }}/oci-factory/oci/traefik/image.yaml
          REPO: ${{ github.repository }}
          SHA: ${{ github.sha }}
          VERSIONS: ${{ inputs.versions }}
        run: |
          cd rock
          versions="${VERSIONS//,/ }"
          ./scripts/generate-image-yaml.sh $versions
          echo "now_epoch=$(date -d now +%s)" >> $GITHUB_OUTPUT

      - name: Commit to the fork
        uses: EndBug/add-and-commit@v9
        with:
          add: "oci/traefik/image.yaml"
          cwd: "./oci-factory"
          message: "chore: Add new traefik releases"
          new_branch: "update-${{ steps.generate-manifest.outputs.now_epoch }}"
          push: "origin update-${{ steps.generate-manifest.outputs.now_epoch }} --force"

      - name: Open a PR from the fork to upstream
        env:
          GH_TOKEN: ${{ secrets.IS_DEVOPS_BOT_TOKEN }}
          OCI_FACTORY_DIR: ${{ github.workspace }}/oci-factory
          SOURCE_REPO: ${{ github.repository }}
        run: ./rock/scripts/open-oci-factory-pr.sh "update-${{ steps.generate-manifest.outputs.now_epoch }}"
